[package]
name = "aoc_2019-12-15"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coffee = { version = "0.3.2", features = ["opengl"] }
intcode = { path = "../intcode" }