[package]
name = "aoc_2020_day_10"
version = "0.1.0"
authors = ["bOli <github@bueechi.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
line_reader = { path = "../line_reader" }
