[package]
name = "advent_of_code_2017"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
line_reader = { path = "../2020/line_reader" }
reformation = "0.5.3"

