[package]
name = "aoc_2019-12-12"
version = "0.1.0"
authors = ["bOli <gitkraken@bueechi.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
num-format = "0.4.0"