[package]
name = "aoc_2019-12-08"
version = "0.1.0"
authors = ["bOli <gitkraken@bueechi.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
